#!/bin/sh

set -u

GREP=/usr/bin/grep
FIND=/usr/bin/find
SORT=/usr/bin/sort
HEAD=/usr/bin/head

code_begin() {
    printf '%s\n' '~~~text'
}

code_end() {
    printf '%s\n' '~~~'
}

echo "# LeoJSON UTF-8 Boundary Inventory"
echo
echo "Generated by: tools/leojson_utf8_boundary_inventory.sh"
echo
echo "## JSONKit UTF / Unicode references"
echo
code_begin
"$GREP" -n -i 'utf8\|utf-8\|utf32\|unicode\|surrogate\|convertutf\|escape' \
    vendor/JSONKit/JSONKit.m vendor/JSONKit/JSONKit.h 2>/dev/null || true
code_end

echo
echo "## LeoUTF8 candidate files"
echo
code_begin
"$FIND" bricks/LeoUTF8 -type f 2>/dev/null | "$SORT" | \
    "$GREP" -E '(\.h|\.c|\.m|\.md)$' || true
code_end

echo
echo "## LeoUTF8 public-looking symbols"
echo
code_begin
"$GREP" -R -n 'LeoUTF8[A-Za-z0-9_]*' bricks/LeoUTF8 2>/dev/null | \
    "$GREP" -E '^[^:]+:[0-9]+:' | \
    "$HEAD" -200 || true
code_end

echo
echo "## Candidate validation symbols"
echo
code_begin
"$GREP" -R -n -i 'valid\|validate\|utf8proc_iterate\|map\|normalize\|codepoint' \
    bricks/LeoUTF8 2>/dev/null | \
    "$HEAD" -200 || true
code_end

echo
echo "## Interpretation placeholder"
echo
echo "- JSONKit owns JSON-internal Unicode behavior."
echo "- LeoUTF8 owns general UTF-8 policy."
echo "- This inventory is informational and does not change runtime behavior."
